DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS sellers;
DROP TABLE IF EXISTS products;
CREATE TABLE clients(id VARCHAR(255) PRIMARY KEY, name VARCHAR(255));
CREATE TABLE sellers(id VARCHAR(255) PRIMARY KEY, name VARCHAR(255));
CREATE TABLE products(id VARCHAR(255) PRIMARY KEY, name VARCHAR(255));